services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aiary-server
    env_file:
      - deploy.env
    depends_on:
      database:
        # database가 확실히 실행되었을 때 spring app을 실행
        condition: service_healthy
    ports:
      - ${SPRING_PORT}:${SPRING_PORT}
    restart: "no"

  database:
    image: mysql:8.4
    container_name: aiary-database
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PW}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PW}
    command:
      --port=${DB_PORT} --max_allowed_packet=32M
    expose:
      - ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: "no"
    volumes:
      - aiary-database:/var/lib/mysql
    # database가 확실히 실행되었을 때 spring app을 실행
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-P",
              "${DB_PORT}", "-u", "${DB_USERNAME}", "-p${DB_PW}" ]

volumes:
  aiary-database: