server:
  port: ${SPRING_PORT}
  servlet:
    session:
      timeout: 3600 # 세션 만료 시간 (3600s, 1h)
      cookie:
        name: JSESSIONID # 세션 쿠키 이름 (기본값)
        http-only: true # JavaScript에서 쿠키 접근 불가 (XSS 방어)
spring:
  application:
    name: be
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PW}

openai:
  api_key: ${OPEN_AI_KEY}